near/near-indexer-for-explorer

- src/configs.rs
- src/main.rs
closes #15 
Command to run Indexer for Explorer updated
Before
```
indexer-binary --home-dir ~/.near/testnet run
```
After
```
indexer-binary --home-dir ~/.near/testnet run --sync-mode from-interruption
indexer-binary --home-dir ~/.near/testnet run --sync-mode last-synced
indexer-binary --home-dir ~/.near/testnet run --sync-mode block --height <block_height>
```
However the "before" command still works and `--sync-mode` default will be `from-interruption`
> feat: Add command arg to choose SyncMode for Streamer

- Cargo.lock
- Cargo.toml
- migrations/2020-10-14-092520_accounts_created_by_receipt_id_nullable/down.sql
- migrations/2020-10-14-092520_accounts_created_by_receipt_id_nullable/up.sql
- src/configs.rs
- src/db_adapters/accounts.rs
- src/main.rs
- src/models/accounts.rs
- src/schema.rs
Closes #13 
Introduce additional parameter to `run` command `--store-genesis` (couldn't find better name) to include handling of genesis file on start of indexer.
Currently if activated will run the function that will walk over `genesis.records` to add records in db with accounts.
~**Note** If account is already present in db this handler will update `created_by_receipt_id` and `deleted_by_receipt_id` by setting them to `NULL` (assuming account is created in genesis and haven't been deleted), one should carefully use it on Indexer restart.~
@frol let me know what do you think about the behaviour described above.
> feat: Add accounts from genesis on start

- migrations/2020-11-06-103108_data_id_add_index/down.sql
- migrations/2020-11-06-103108_data_id_add_index/up.sql
- migrations/2020-11-06-104009_chunkd_index/down.sql
- migrations/2020-11-06-104009_chunkd_index/up.sql
- src/db_adapters/receipts.rs
It appears to happen only in case of data-receipts, because we can't find previous receipt by `receipt_id`. Instead we need to look for receipt via `data_id` through `receipts_action_output_data`. I've changed the way we're looking for parent transaction for receipts to differentiate action-receipts and data-receipts.
fixes #39 
also closes #36
> fix: Fix/missing parent for receipt

- migrations/2020-11-06-113536_account_id_suffix/down.sql
- migrations/2020-11-06-113536_account_id_suffix/up.sql
- src/models/execution_outcomes.rs
- src/models/receipts.rs
- src/schema.rs
> refator: Rename account ID columns to include `_account_id` suffix

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db_adapters/access_keys.rs
- src/db_adapters/account_changes.rs
- src/db_adapters/accounts.rs
- src/db_adapters/blocks.rs
- src/db_adapters/chunks.rs
- src/db_adapters/execution_outcomes.rs
- src/db_adapters/receipts.rs
- src/db_adapters/transactions.rs
- src/main.rs
- src/models/mod.rs
Note: this is already compiled a few weeks ago, testnet is already using this version of NEAR Indexer for Explorer
> refactor: Upgrade dependencies and migrate from tokio-diesel to actix-diesel

- migrations/2020-12-07-153402_initial_schema/up.sql
Resolves https://github.com/near/near-indexer-for-explorer/issues/74#issuecomment-800721467
We failed to squash the 0.2.x migrations properly and did not stumble upon the issue before since we gradually upgraded the database instead of wiping it completely on our end.
There is no need for a new migration since with the original migration, nothing could be indexed properly anyway, so we just need to fix that initial migration.
> fix: Fixed the type for accounts.id and account_changes.id to be auto-incrementing (bigserial)

- README.md
NOTE: The database instances referenced in the README are read-only replicas.
> docs: Added public read-only credentials to the Indexer for Explorer database

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Bump version to 0.6.2
Based on commit hash from [1.19.0-rc.2](https://github.com/near/nearcore/releases/tag/1.19.0-rc.2)
> refactor: Upgrade nearcore dependency. Bump version to 0.6.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db_adapters/accounts.rs
Fixes #68 
Also I've changed `nearcore` dependency hash to the release hash of [1.19.0](https://github.com/near/nearcore/releases/tag/1.19.0) Only a version has changed in that commit in compare with previous, but I decided to stick to the release as it is perfect timing for that.
I've tried to leave comments and renamed some variables as I've found them a bit misleading.
> fix: Handle recreation of implicit accounts properly to avoid confusion for the users

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- migrations/2021-05-27-154211_account_changes_unique_idx/down.sql
- migrations/2021-05-27-154211_account_changes_unique_idx/up.sql
See an example:
```
select * from account_changes 
where account_changes.affected_account_id = '0520974a09c1e419a208b9238363df42df30ff94.lockup.near' 
and account_changes.changed_in_block_timestamp = 1604431876987521027 
and account_changes.caused_by_receipt_id = 'HUEGvT8ceLGWgGyx2o8vsSgoRnSEkpgJsi4UbeiaMsXJ'
order by account_changes.changed_in_block_timestamp desc, id desc;
```
In the result, all the columns are the same except `update_reason`: it's `ACTION_RECEIPT_GAS_REWARD` and `RECEIPT_PROCESSING`, in the same block and receipt
So we should put `update_reason` to index also.
This one is also not OK for the same reason, and I'm not sure what should we do with it. Honestly, we could just delete it, it does nothing. Is it OK to remove this line in this PR also? …
> fix: unique indexes in account_changes table should contain update_reason

- Cargo.lock
Upgraded openssl-sys to include the patches for:
* https://nvd.nist.gov/vuln/detail/CVE-2021-3450
* https://nvd.nist.gov/vuln/detail/CVE-2021-3449
> deps: Upgraded openssl-sys to 111.15.0+1.1.1k

- migrations/2021-08-02-183200_transactions_sorting_idx/down.sql
- migrations/2021-08-02-183200_transactions_sorting_idx/up.sql
Resolves #135 
To apply it to mainnet, we should use 
```sql
CREATE INDEX CONCURRENTLY transactions_sorting_idx ON transactions(block_timestamp, index_in_chunk);
```
(We never put `CONCURRENTLY` to migration files, I decided that I should be consistent here)
Applying it to `35.233.39.106` (it's copy of mainnet with data till 10th of May 2021) took 75 seconds.
Select from @frol works in a moment.
Important: columns `block_timestamp, index_in_chunk`should always go in this order, and we should specify `desc` for both or for no columns. That anyway sounds logical.
```sql
select pg_size_pretty(pg_table_size('transactions_sorting_idx'));
```
For 14M lines, it took 550 MB of storage. Mainnet has 17M lines, so hopefully it should not be so far from these numbers.
Can I apply it to mainnet?
> feat: speed up sorting in transactions

- migrations/2021-08-06-123500_account_changes_ordering_column/down.sql
- migrations/2021-08-06-123500_account_changes_ordering_column/up.sql
- src/db_adapters/account_changes.rs
- src/models/account_changes.rs
- src/schema.rs
*Partially resolves #77* (this PR introduces an easy way to sort the account changing events: `ORDER BY changed_in_block_timestamp, index_in_block`)
I am still waiting for the server updates, want to test it on the production-like env, that's why I marked it as a draft.
We should apply the migration by pieces, otherwise, it will take too long to update existing lines.
> feat: introduced an easy way to sort account_changes in their correct historical order (changed_in_block_timestamp + index_in_block)

- migrations/2021-08-06-123500_account_changes_ordering_column/up.sql
sqlalchemy is too smart,
it decides whether we need to commit changes
based on first line of raw sql statement.
https://stackoverflow.com/questions/45347565/executing-multiple-statements-with-postgresql-via-sqlalchemy-does-not-persist-ch
It was a script from Bohdan
https://github.com/near/near-indexer-for-explorer/pull/99#issuecomment-838871700
Bohdan's update started from `UPDATE` and everything worked.
Mine started from `WITH` and sqlalchemy decided not to commit anything because of that.
We lost some logging, but at least it works
It runs now on `34.141.101.9` for testnet
> fix: update python script inside account_changes adding index_in_block migration

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/configs.rs
- src/db_adapters/receipts.rs
- src/main.rs
Fixes #163 
I've bumped the version to `0.10.0` because I've dropped the `--allow-missing-relations-in-first-blocks` flag completely. It **doesn't mean** this PR is going to be released once merged.
* Dropped `--allow-missing-relations-in-first-blocks` flag completely
* Add the flag `--non-strict-mode` which: 
* changes retry attempts on Receipts from 10 to 4
* stops saving `account_changes` completely as it is impossible to save in case of missing of related Receipts
* Add the flag `--stop-after-number-of-blocks N` which namely stops the indexer after processing N blocks
All those flags and features are useful for debugging or emergency purposes. They are not supposed to be used in normal circumstances.
> refactor: Strict/Non-strict mode improvements

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Due to a fix being released to mainnet we need
this migration to be able to use the latest archive backups on mainnet.
> fix(nearcore) Upgrade nearcore

- README.md
I added it here as the migration
https://github.com/near/near-indexer-for-explorer/blob/master/migrations/2021-06-09-102523_grant_select_on_new_tables/up.sql
But I always forget to run it in all new DBs
I'm copy-pasting the code from here
It will be easier to fix the source
> doc: add select privilege by default to all users

- src/db_adapters/blocks.rs
@khorolets There is no urgency at the moment, but the next time we would need to check something, let's check if this fix resolves the issue.
> fix: Long boot time on start from interruption was apparently due to the fact that we loaded all the blocks, ooops

- Cargo.lock
We need Cargo.lock to fix weird segmentation fault issue. It seems actix got messed up during the previous global dependencies update
> hotfix: reverted Cargo.lock

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* Bump version to `0.10.4`
* #203 
* Fix `from-interruption` performance issue
> refactor: 0.10.4 (nearcore 1.23.0 + hash collisions solution)

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
A protocol upgrade is going to happen in `1.23.1-rc.1` we need to follow to prevent our nodes from being stuck
> refactor: Upgrade nearcore to 1.23.1-rc.1

- Cargo.lock
- Cargo.toml
- src/configs.rs
- src/db_adapters/execution_outcomes.rs
- src/db_adapters/receipts.rs
- src/db_adapters/transactions.rs
- src/main.rs
- src/models/transactions.rs
Resolves #229 
* I've added the `--debug` flag and the first `indexer_for_explorer` debug message to reason about how the cache is working, it should allow us to put some more logs if needed
* Add `ReceiptCache` which is a `HashMap` of accordance between Receipt ID and parent Transaction hash. 
The working flow looks like this:
* First we handle transactions and we store the pair `converted_into_receipt_id: transaction_hash` to the cache
* When processing receipts we look into the cache to get a parent transaction hash for each of the receipts
* [Fallback logic] If we don't observe parent transaction hash for specific receipts we are looking for them in the database
* ExecutionOutcomes stage. We are interested in those outcomes that result in another receipt(s). We get all those receipts' …
> refactor: Add ReceiptsCache to decrease the number of unnecessary SELECT queries to the database

- src/db_adapters/execution_outcomes.rs
- src/db_adapters/receipts.rs
- src/db_adapters/transactions.rs
- src/main.rs
Resolves #242 
* Replace type alias `ReceiptIdString` with `ReceiptOrDataId` enum
* Cache parent transaction hash for Data Receipts (it is necessary to do in a different way)
> refactor: Improve ReceiptsCache to handle Data Receipts and some optimization

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* Add [FT events](https://nomicon.io/Standards/FungibleToken/Event.html) support: `assets__fungible_token_events` table stores the information about FT `mint`, `transfer`, `burn` events
* Add index on `action_receipt_actions` table. Applying migration could take some time
* Introduce `ReceiptsCache` to optimize the way we match `Receipts` with parent `Transactions`
* Upgrade nearcore to `1.24.0-rc.2`
> refactor: Upgrade nearcore to 1.24.0-rc.2

- migrations/2022-06-07-000000_drop_action_receipt_actions_args_amount_index/down.sql
- migrations/2022-06-07-000000_drop_action_receipt_actions_args_amount_index/up.sql
Reverting `action_receipt_actions_args_amount_idx` index that was added in #99. This is needed to avoid potential problems when the `amount` argument in the receipt actions is not indexable.
> fix: dropped the args_json->amount index on action_receipt_actions table

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
https://github.com/near/nearcore/releases/tag/1.29.0-rc.2
> release: indexer-for-explorer 0.10.24 with nearcore updated to 1.29.0-rc.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
The release includes the fix for #305
We will update testnet nodes once the release is cut.
> chore: Release 0.10.25

- CHANGELOG.md
- Cargo.toml
- src/models/serializers.rs
This PR fixes function args extraction (`args->args_json`) for actions (`action_receipt_actions` and `transaction_actions` tables). This bug affected all the records since 0.10.22 release. Consider removing and re-indexing all the records from the time you deployed 0.10.22+ release. I will also provide a patch that you can use to re-index without cleaning up the database and instead just run it over the existing data, so it will forcefully update the data.
> fix: Action args_json must be extracted correctly whenever possible

- CHANGELOG.md
- src/db_adapters/access_keys.rs
- src/main.rs
This PR refactors the `access_keys` logic to be driven from [`StateChanges`](https://near-indexers.io/docs/data-flow-and-structures/structures/state_change#statechangewithcauseview) rather than [`ExecutionOutcomes`](https://near-indexers.io/docs/data-flow-and-structures/structures/execution_outcome), allowing us to remove the logic which indirectly creates an access key on every transfer to an implicit account. This means access keys will only be written when the implicit account is first created, and ignore subsequent transfers. Resolves https://github.com/near/near-indexer-for-explorer/issues/304.
Test plan:
> fix: Avoid recreating access key on transfer to implicit account

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
⚠️ This PR targets `master-nearcore` rather than `master` as we'll most likely be merging #326 soon.
> chore: Upgrade `nearcore` to `1.30.0`

- README.md
- database/migrations/2023-02-02-100000_fungible_token_events_pk_changed/down.sql
- database/migrations/2023-02-02-100000_fungible_token_events_pk_changed/up.sql
- database/migrations/2023-02-02-110000_non_fungible_token_events_pk_changed/down.sql
- database/migrations/2023-02-02-110000_non_fungible_token_events_pk_changed/up.sql
These changes have a major issue: when someone runs the project on the empty DB, the final state will not be accurate. I have no idea how to force users to read the migrations and run something manually.
I can uncomment everything and drop `CONCURRENTLY`: in this case, people with empty DB will be happy, while the others will have few hours blocking operation, which is unacceptable.
What do you guys think?
> fix: improve performance of assets__* by changing PKs

- README.md
- database/migrations/2023-02-02-100000_fungible_token_events_pk_changed/down.sql
- database/migrations/2023-02-02-100000_fungible_token_events_pk_changed/up.sql
- database/migrations/2023-02-02-110000_non_fungible_token_events_pk_changed/down.sql
- database/migrations/2023-02-02-110000_non_fungible_token_events_pk_changed/up.sql
I realised that we cheat on our users in the previous PR #343. 
It's been a long time when we add the migrations which is impossible to apply on the full DB: we just know about that and apply these changes manually with `CONCURRENTLY` option enabled.
I fixed the last 2 transactions so that it works well on the empty DB;
I also added the explanations to the README, adding the instruction how to apply the new migrations on the full DB.
> fix: rewrite last assets migrations, update readme

- README.md
- database/Cargo.toml
- database/src/adapters/assets/events.rs
- database/src/adapters/assets/mod.rs
- indexer/Cargo.toml
- indexer/src/main.rs
> Add feature flag on account_changes and fungible_token_events

- indexer/src/configs.rs
With these changes, we:
- fail early if we have DB error
- start 500 blocks before the last block to be sure we haven't missed anything
- start from the beginning if the DB is empty
> feat: rewrite start-from-interruption logic

- database/src/adapters/execution_outcomes.rs
- database/src/adapters/receipts.rs
- database/src/adapters/transactions.rs
- database/src/receipts_cache.rs
- indexer/src/main.rs
I've made some refactoring before I'll introduce meta tx support logic
1. get rid of `std::sync::Arc::clone` because it looks scary to me, we can just use `.clone()` instead, the same method is used
2. split the methods. I'll add more logic to some of them further
3. parallelize receipts tables inserts, it should work a little faster with this change
4. fix a small bug in `transaction_actions`: tx_hash for duplicated transaction will point out to its parent instead of the first original tx
> refactor: rearrange methods in tx_actions, receipt_actions

- indexer/src/configs.rs
This PR adds the support of `betanet` chain introduced in `near-lake-framework` 0.7.0
I believe most users won't need it, but it's a step in our work in creating an environment for international testing.
**Note**, this PR is created against `meta_tx` branch and wants to be merged into #361
> feat: Add the support of betanet (added with lake-framework-0.7.0)

- Cargo.lock
- indexer/CHANGELOG.md
- indexer/Cargo.toml
- Bump version
- Update CHANGELOG
FYI I have deleted the 0.12.0 release since it is broken
> chore: Release 0.12.1 (bump version, update changelog)

- circulating-supply/Cargo.toml
- circulating-supply/src/lockup.rs
Version `0.15` of `near-jsonrpc-primitives` returns values which are already `base64` decoded, making our manual decoding superfluous. When upgrading `0.16` we forgot to remove it, removing it now to fix the circulating supply computation.
> fix: Remove decoding of lockup contract as its now handled by nearcore

- database/diesel.toml
- database/migrations/2023-04-20-160000_deprecated_namespace/down.sql
- database/migrations/2023-04-20-160000_deprecated_namespace/up.sql
- database/src/schema.patch
- database/src/schema.rs
I tried to restrict selecting from 2 tables (see the full story [here](https://github.com/near/near-indexer-for-explorer/discussions/351)). I came to the conclusion that managed Postgres does not allow this.
That's why I created a `deprecated` schema, the users will not have access to it by default.
My plan is to move these tables to `deprecated` schema, hide them from all the users and see what happens.
We will still write the data to that tables.
If we break something important, we will grant access to the tables and consider how to fix it.
After a month of silence, we can drop them completely.
More tech details on what's going on here:
- Added migration
- Updated `schema.patch` so that it can generate the correct `schema.rs` file, it was a little broken
- Add the explanation of how …
> Hide tables to a separate schema

- database/src/retryable.rs
We can have FK violation on transactions and receipts and it's our normal behaviour (we insert in an optimistica way, and the inserts usually go fine from 2 attempt)
> fix: change log severity

- database/src/adapters/execution_outcomes.rs
- database/src/adapters/receipts.rs
- indexer/src/main.rs
During our last refactoring sessions, we haven't paid enough attention to the `non-strict mode` for a while. Thus, this mode lost its nature and became too strict for its name. 
In this PR I've improved this mode to help us to get back on track:
- In non-strict mode we don't waste time and don't even attempt to find parent tx hash for the receipt in the DB (slow `SELECT`-queries make no sense for non-strict mode by slowing it down)
- The amount of attempts to store `ExecutionOutcomes` is reduced to 5 to complete in meaningful time (1600 ms or so)
- Prevent the entire indexer from shutting down if `handle_message` returns an error. Instead, we display a warning and proceed to the next block.
I've made a local check with an empty database setup and run an indexer with `non-strict-mode` + …
> refactor: Improve non-strict-mode to make it even less strict

- indexer/src/main.rs
The use of `concurrency` has been removed somehow - this PR adds it back in.
> fix: Correctly use `concurrency` config option
