- Cargo.lock
- Cargo.toml
- src/main.rs
- src/models/access_keys.rs
- src/models/accounts.rs
- src/models/actions.rs
- src/models/chunks.rs
- src/models/mod.rs
- src/models/receipts.rs
Also remove the outdated code that handles outcomes, transactions, receipts, access keys, accounts
Closes #1
> refactor: Upgrade indexer framework version

- Cargo.lock
- Cargo.toml
- diesel.toml
- migrations/2020-10-06-111219_create_accounts/down.sql
- migrations/2020-10-06-111219_create_accounts/up.sql
- src/db_adapters/accounts.rs
- src/db_adapters/execution_outcomes.rs
- src/db_adapters/mod.rs
- src/db_adapters/receipts.rs
- src/main.rs
- src/models/accounts.rs
- src/models/mod.rs
- src/models/transactions.rs
- src/schema.rs
> feat: index accounts from receipt execution outcomes

- src/db_adapters/accounts.rs
> feat: Include implicit accounts to Accounts handler

- Cargo.lock
- Cargo.toml
- diesel.toml
- migrations/2020-10-15-093744_receipts-fk-constraints/down.sql
- migrations/2020-10-15-093744_receipts-fk-constraints/up.sql
- migrations/2020-10-15-114122_create_access_keys/down.sql
- migrations/2020-10-15-114122_create_access_keys/up.sql
- src/db_adapters/access_keys.rs
- src/db_adapters/mod.rs
- src/db_adapters/receipts.rs
- src/main.rs
- src/models/access_keys.rs
- src/models/enums.rs
- src/models/mod.rs
- src/schema.rs
> feat: Extract AccessKeys from receipts (like we do in Indexer forExtract AccessKeys from receipts (like we do in Indexer for Wallet)

- migrations/2020-10-26-113101_remove_account_fk_from_access_keys/down.sql
- migrations/2020-10-26-113101_remove_account_fk_from_access_keys/up.sql
- src/configs.rs
- src/db_adapters/receipts.rs
- src/main.rs
- src/models/mod.rs
- src/models/serializers.rs
> refacor: Strict mode

- Cargo.lock
- Cargo.toml
- migrations/2020-05-18-095055_create_blocks/up.sql
- migrations/2020-05-19-132810_create_chunks/up.sql
- migrations/2020-09-17-130740_create_receipts/up.sql
- migrations/2020-09-23-101219_create_transactions/up.sql
- src/db_adapters/receipts.rs
- src/db_adapters/transactions.rs
- src/main.rs
- src/models/blocks.rs
- src/models/chunks.rs
- src/models/receipts.rs
- src/models/transactions.rs
- src/schema.rs
> feat: Index in chunk and block timestamp for txs and receipts. Author account id to blocks and chunks.

- src/db_adapters/accounts.rs
- src/db_adapters/receipts.rs
- src/models/accounts.rs
Fixes #32 
In this PR I'm resolving the first part of the issue.
> refactor: Resolve conflicting/duplicating CreateAccount/DeleteAccount actions

- migrations/2020-11-09-152330_sanity-naming/down.sql
- migrations/2020-11-09-152330_sanity-naming/up.sql
- src/db_adapters/access_keys.rs
- src/main.rs
- src/models/access_keys.rs
- src/models/enums.rs
> feat: Add access keys from genesis to store genesis handler

- migrations/2020-11-13-150029_last_update_block_height/down.sql
- migrations/2020-11-13-150029_last_update_block_height/up.sql
- src/db_adapters/access_keys.rs
- src/db_adapters/accounts.rs
- src/main.rs
- src/models/access_keys.rs
- src/models/accounts.rs
- src/schema.rs
> refactor: Make the updates/inserts idempotent on access keys

- Cargo.lock
- Cargo.toml
- migrations/2020-09-23-075746_create_execution_outcomes/up.sql
- src/db_adapters/access_keys.rs
- src/db_adapters/accounts.rs
- src/db_adapters/execution_outcomes.rs
- src/main.rs
- src/models/execution_outcomes.rs
- src/schema.rs
> refactor: Add order-preserving columns to execution outcomes

- Cargo.lock
- Cargo.toml
- src/configs.rs
- src/main.rs
Closes #51 
~~Making it draft to wait for https://github.com/near/nearcore/pull/3636 to be merged to update dependency hash~~
> feat: Introduce a CLI option to force syncing blocks when still in "is_syncing" mode

- Cargo.lock
- Cargo.toml
- src/db_adapters/access_keys.rs
- src/db_adapters/accounts.rs
- src/db_adapters/blocks.rs
- src/db_adapters/chunks.rs
- src/db_adapters/execution_outcomes.rs
- src/db_adapters/receipts.rs
- src/db_adapters/transactions.rs
- src/main.rs
Fixes #48 
As we investigated we saw that nothing is missing actually but sometimes it is delayed to be stores because of collisions between retries. We decided to increase the delay between attempts up to 2 min to give them a chance to be applied successfully.
> fix: Investigate missing chunks

- migrations/2021-01-14-170424_index-receipt-originated-from-transaction-hash/down.sql
- migrations/2021-01-14-170424_index-receipt-originated-from-transaction-hash/up.sql
> feat: Add index on receipts.originated_from_transaction_hash

- CHANGELOG.md
- src/db_adapters/access_keys.rs
- src/db_adapters/accounts.rs
- src/main.rs
> fix: Fill delete_by_receipt_id of access keys when owner account is deleted

- migrations/2021-01-20-152056_index-transactions-receiver-account-id/down.sql
- migrations/2021-01-20-152056_index-transactions-receiver-account-id/up.sql
> feat: Add migration to add index for transactions.receiver_account_id

- .buildkite/pipeline.yml
- src/db_adapters/access_keys.rs
- src/db_adapters/accounts.rs
- src/db_adapters/chunks.rs
- src/db_adapters/execution_outcomes.rs
- src/models/mod.rs
Test job to verify this works: https://buildkite.com/nearprotocol/near-indexer-for-explorer/builds/1. After fail fixed formatting.
> feat(buildkite): initial setup

- migrations/2021-03-11-123839_index-action-kind-and-status/down.sql
- migrations/2021-03-11-123839_index-action-kind-and-status/up.sql
> Add indecies on action_kind and status (execution_outcome_status)

- README.md
Closes #79: Add README on adding new read-only accounts to PostgreSQL
> feat: Add README on adding new read-only accounts to PostgreSQL

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/configs.rs
- src/db_adapters/blocks.rs
- src/main.rs
- src/models/blocks.rs
> feat: Improve sync-from-interruption mode

- README.md
> docs: Add the instruction how to debug locally

- migrations/2021-05-27-154211_account_changes_unique_idx/down.sql
- migrations/2021-05-27-154211_account_changes_unique_idx/up.sql
Fixes https://github.com/near/near-indexer-for-explorer/issues/74
> fix: add unique indexes on account_changes table

- migrations/2021-06-02-173100_add_migration_state_change_reason_kind/down.sql
- migrations/2021-06-02-173100_add_migration_state_change_reason_kind/up.sql
- src/models/enums.rs
> feat: add new change reason kind MIGRATION

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/configs.rs
- src/main.rs
- src/models/serializers.rs
> fix: ADD_KEY actions with FUNCTION_CALL permissions cannot be stored in the DB

- migrations/2021-08-11-163800_account_changes_ordering_idx/down.sql
- migrations/2021-08-11-163800_account_changes_ordering_idx/up.sql
> feat: add account changes sorting index

- CONTRIBUTING.md
My checklist from https://telegra.ph/I-survived-after-Rust-review-with-76-comments-and-came-up-with-this-checklist-08-12
(without meme)
> feat: add the checklist for contributors

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/models/serializers.rs
Should address #159 once deployed
> fix: Change receiver_id type to String to be compatible with nearcore

- README.md
Modify the concurrent value of command parameters when the README.md page is started
> Modify page README.md

- src/db_adapters/assets/non_fungible_token_events.rs
> fix(NFT): the contract_id for NFTs from receiver.

- src/db_adapters/assets/non_fungible_token_events.rs
Small fix from https://github.com/near/near-indexer-for-explorer/pull/169#discussion_r744556104
> fix: get rid of creating vector

- src/db_adapters/receipts.rs
- src/db_adapters/transactions.rs
- src/main.rs
- src/models/receipts.rs
- src/models/transactions.rs
This PR will hopefully close #84 in one day
> Handle collisions in transactions table

- README.md
> fix: Update README with proper replacement of `--download` key

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/main.rs
* Bump version to 0.10.6
* Upgrade `nearcore` dependency to 1.23.1-rc.2
> refactor: Upgrade nearcore to 1.23.1-rc.2

- README.md
- migrations/2021-11-09-191400_timeout_for_public_readonly/down.sql
- migrations/2021-11-09-191400_timeout_for_public_readonly/up.sql
Continuing https://github.com/near/near-indexer-for-explorer/pull/217
> fix(migrations): remove migration with altering readonly role

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* Bump version to `0.10.7`
* Upgrade nearcore to `1.23.1`
> refactor: Upgrade to nearcore 1.23.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db_adapters/access_keys.rs
- src/main.rs
* Upgrade nearcore to `1.24.0-rc.1`
* Small changes to `near_indexer::init_configs()` call
> refactor: Upgrade nearcore to 1.24.0-rc.1

- README.md
@khorolets 
Type: doc
Updating incorrect database size figures in the README.md with figures provided to me by @khorolets.
> Updated README.md -  incorrect figures for DB size

- CHANGELOG.md
Collected all my stuff that needs to be mentioned.
Please add there all other things and merge when it's needed
> doc: add draft changenotes

- README.md
Without this option, users can't log in into db
> Add login option for creating user

- src/main.rs
> fix: indexer-explorer --version panics

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Upgrade to the patch (for testnet)
> chore: Upgrade nearcore to 1.30.0-patch

- CONTRIBUTING.md
> doc: Cargo.toml fomatting guide

- indexer/src/main.rs
copy-pasted from https://github.com/near/near-lake-framework-rs#example
> fix: handle streamer result properly

- Cargo.lock
- circulating-supply/Dockerfile
- indexer/Dockerfile
Plus update Cargo.lock, I missed this change before
> fix: update Dockerfiles with new Rust version

- database/src/models/serializers.rs
Some time ago since `near-primitives` and `near-indexer-primitives` of version `0.15.0` arguments in some of the structures on the `nearcore` became pure `Vec<u8>` instead of base64-encoded `String`.
I remember a few PRs with the relevant changes on our side:
- #297 
- #306 
Which were overwritten back since we couldn't upgrade from `0.14.0` version of the primitives here #326 
Since the #361 we upgraded to `0.16.0` version of the primitives and now we have the same issue that we had with the attempt to migrate to `*-primitives-0.15.0`.
With this PR I am applying the changes necessary to handle the `Vec<u8>` data properly before storing it in the database.
We must release `0.12.1` in order for all of this to work before deploying and mark `0.12.0` as broken (consider even deleting the …
> fix: Action's args serialization to base64

- indexer/Cargo.toml
Indexer for explorer still inserting into DB
> Fix remove feature fungible_token_events
